/** 状态机代码与默认状态集（迁移表数据化存 DB，此处为类型与种子基线，GBR-6） */
export const STATE_MACHINES = {
  ORDER: [
    "DRAFT", "PLACED", "PAID_ESCROW", "CONFIRMED", "PREPARING", "SHIPPED",
    "IN_CUSTOMS", "CUSTOMS_CLEARED", "DELIVERED", "COMPLETED",
    "CANCELLED", "DISPUTED", "RESOLVED",
  ],
  AUCTION: ["SCHEDULED", "ACTIVE", "CLOSED", "SETTLED", "CANCELLED"],
  CUSTOMS: ["DRAFT", "SUBMITTED", "INSPECTION", "CLEARED", "REJECTED"],
  DISPUTE: ["OPEN", "INVESTIGATING", "RESOLVED_REFUND", "RESOLVED_PARTIAL", "RESOLVED_REJECT"],
  OPPORTUNITY: ["NEW", "CONTACTED", "NEGOTIATING", "WON", "LOST"],
  FUTURES: ["PUBLISHED", "SUBSCRIBED", "CONFIRMING", "SETTLED", "DEFAULTED", "CANCELLED"],
  RFQ: ["OPEN", "QUOTING", "ACCEPTED", "EXPIRED", "CANCELLED"],
  SHIPMENT: ["PREPARING", "IN_TRANSIT", "ARRIVED", "DELIVERED", "EXCEPTION"],
} as const;
export type StateMachineCode = keyof typeof STATE_MACHINES;
export type OrderState = (typeof STATE_MACHINES.ORDER)[number];
